In [4]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import os

# Load the data

# Scelta automatica del Path locale tra "paoloartasensi" o "lorenzobassetti"
path = '/Users/paoloartasensi/Python_Scripts/'
isdir = os.path.isdir(path)
if isdir == True:
    path = '/Users/paoloartasensi/Python_Scripts/'
else:
    path = '/Users/lorenzobassetti/Dropbox/Quant/Python_DEV/'


path = (path+'/wow/data_modelli/sq_bax_1207_1.csv')
df = pd.read_csv(path, sep=';', decimal='.')
df.set_index('Time', inplace=True)

In [5]:
df

,Ax,Ay,Az,Gx,Gy,Gz,BAR,P,R,UP,DOWN,prob
Time,,,,,,,,,,,,
1670422691444,10.14291,-0.78796,4.04758,6.16000,2.17000,-5.18000,986.34741,0,0,0,0,1
1670422691546,8.75859,-1.01070,3.54223,26.66999,3.08000,-2.87000,986.35059,0,0,0,0,1
1670422691646,9.34297,-0.91250,2.89558,29.39999,0.84000,13.30000,986.33740,0,0,0,0,1
1670422691746,10.34649,0.14610,2.75906,38.98999,13.92999,20.78999,986.34351,0,0,0,0,1
1670422691848,10.66263,1.52563,3.32429,21.62999,-1.19000,1.47000,986.32715,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1670422750952,9.97286,-0.54606,2.20102,5.53000,-3.01000,5.25000,986.41870,0,0,0,1,1
1670422751055,10.13333,-0.78557,2.04774,2.03000,-3.22000,-2.03000,986.41797,0,0,0,1,1
1670422751154,9.63995,-0.91250,2.28245,0.77000,3.50000,6.37000,986.43164,0,0,0,1,1
1670422751257,10.14770,-0.96759,2.27048,-0.21000,2.03000,4.55000,986.40747,0,0,0,1,1
1670422751357,9.90341,-1.03225,2.41418,-0.49000,0.70000,2.17000,986.38892,0,0,0,1,1

In [6]:

# Split the data into features (X) and labels (y)
X = df.drop("DOWN", axis=1)
y = df["DOWN"]

# Scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25)

# Create and fit the SVM model
model = SVC(kernel='linear')
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate and print the accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

Accuracy: 97.99%